export class Element{
    inputName = 'input[placeholder="Full Name"]'
    inputEmail = 'input[placeholder="name@example.com"]'
    inputCurrentAddress = 'textarea[placeholder="Current Address"]'
    inputPermanentAddress = '#permanentAddress'
    checkboxExpand = '.rc-tree-switcher.rc-tree-switcher_close'
    homeCheckbox = '.rc-tree-checkbox[aria-label="Select Home"]'
    downloadsCheckbox = '.rc-tree-checkbox[aria-label="Select Downloads"]'
    yesRadioBtn = 'label[for="yesRadio"]'
    impressiveRadioBtn = 'label[for="impressiveRadio"]'
    noRadioBtn = 'label[for="noRadio"]'
    inputFirstName = 'input[placeholder="First Name"]'
    inputLastName = 'input[placeholder="Last Name"]'
    inputAge = 'input[placeholder="Age"]'
    inputSalary = 'input[placeholder="Salary"]'
    inputDepartment = 'input[placeholder="Department"]'
    searchBar = 'input[placeholder="Type to search"]'
    editBtn = 'span[title="Edit"]'
}